# This is a basic workflow to help you get started with Actions

name: 'Test Checkov for Terraform GitHub Actions'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'Checkov-Terraform'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Static Checks'
        run: |
          docker pull bridgecrew/checkov
          PWD=`pwd`
          pwd
          docker run -t -v /terraform_CI-CD-test/tf:/tf bridgecrew/checkov -d $PWD  
